### ISSUE TITLE
Disable sorting on certain columns

### ISSUE THREAD

**Issue by Rob-Post** [DevExpress/devextreme-reactive#473] opened 2017-11-10 10:12 UTC
Hi,

I have a grid with multiple columns with sorting enabled. In the first column an image is shown and in the second column a name. I don't want people to be able to sort on the image. Is it possible to disable the sorting on a particular column?

Thanks,

Rob

**Comment by kvet** [comment] 2017-11-10 11:19
Hi,
 
It is not currently possible to do this with a high-level API, but we plan to add this feature in future releases. As a workaround, I can suggest you override headerCellTemplate in the TableHeaderRowPlugin.

**Comment by gsobolev** [comment] 2017-11-13 11:50
Hi,
 
We are closing this issue as a duplicate of #363.

**Closed by gsobolev** 2017-11-13 11:50 UTC
Labels: duplicate, enhancement
