### ISSUE TITLE
Question: Position of edit/delete buttons

### ISSUE THREAD

**Issue by ddmedeiros** [DevExpress/devextreme-reactive#348] opened 2017-09-19 18:18 UTC
Is there a way to change the position of edit/delete buttons to the right side of the grid ?

**Comment by bhavin-00** [comment] 2017-09-20 04:42
https://stackblitz.com/edit/react-pzyqxc?file=index.js

**Comment by kvet** [comment] 2017-09-20 07:03
Hi,
 
I will close the issue as it is a duplicate of #287.

**Closed by kvet** 2017-09-20 07:03 UTC
Labels: duplicate
