### ISSUE TITLE
update to MUI v0.20.0?

### ISSUE THREAD

**Issue by mikeriley131** [DevExpress/devextreme-reactive#550] opened 2017-12-04 19:27 UTC
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Dependency is on MUI v1.0.0-beta

Get the following error when updating MUI to v0.20.0:
```
Failed to compile
./node_modules/@devexpress/dx-react-grid-material-ui/dist/dx-react-grid-material-ui.es.js
1071:4-18 'material-ui' does not contain an export named 'TableSortLabel'.
```

### Expected Behaviour
Ideally, would update to work with MUI v0.20.0

**Comment by aislanmaia** [comment] 2017-12-04 21:44
I believe this grid is intended to be working with the next generation of Material-UI, the v1.0.x

**Comment by mikeriley131** [comment] 2017-12-04 21:50
Yeah, it was just updated to v0.20.0 (https://github.com/mui-org/material-ui/releases), but there appears to be a breaking change. `TableSortLabel` is no longer included.

**Comment by kvet** [comment] 2017-12-05 08:51
Hi,
 
This issue is a duplicate of: https://github.com/DevExpress/devextreme-reactive/issues/302

**Closed by kvet** 2017-12-05 08:51 UTC
Labels: duplicate, question
