### ISSUE TITLE
is there any way to freeze the selected columns 

### ISSUE THREAD

**Issue by iiitmanikanta** [DevExpress/devextreme-reactive#341] opened 2017-09-18 07:28 UTC
it's very helpful to have freezing columns option. at least for the first one or two coloumns.

**Comment by terndrup** [comment] 2017-09-18 08:45
This is on the roadmap see #335 #293 

Fingers crossed it comes soon! :)

**Comment by gsobolev** [comment] 2017-11-10 15:15
Hi,
 
We are closing this issue as a duplicate of #293.

**Closed by gsobolev** 2017-11-10 15:15 UTC
Labels: duplicate
