### ISSUE TITLE
Grid: Virtual scrolling - Part of scrollbar not visible (Edge)

### ISSUE THREAD

**Issue by joerneu** [DevExpress/devextreme-reactive#1556] opened 2018-11-01 16:49 UTC
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart

### Current Behaviour

With Edge part of the vertical scrollbar is not visible and cannot be used:

![reactgridedgescrollbar](https://user-images.githubusercontent.com/31096117/47866226-74742300-ddfe-11e8-8f47-a047f5702b83.jpg)

### Expected Behaviour

Same layout and behavior as other browsers.

### Steps to Reproduce (for Bugs)

[Virtual scrolling demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/)

- Select "Bootstrap 4"

### Environment

- browser: Edge
- bootstrap: 4

**Comment by joerneu** [comment] 2018-11-01 17:16
Found another instance where part of a scrollbar is not visible: (No virtual scrolling)

![reactgridedgescrollbar2](https://user-images.githubusercontent.com/31096117/47867333-860afa00-de01-11e8-8da4-a661378fc77e.jpg)

[Data editing demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/data-editing/)

(I found so many issues just looking at the Demos that I am wondering if Edge is missing from your browser tests?)

**Comment by ushkal** [comment] 2018-11-08 11:59
Hi,

We found that this issue is caused by the following bug in the Edge browser: [Sticky element overlaps a scrollbar of a container element](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19567115/) We won't fix this problem as it is related to the browser.

**Comment by ushkal** [comment] 2018-11-14 11:13
We discussed the issue again and decided to fix it on our side. In the meantime, you can use the following workaround:
```javascript
const Container = ({ style, ...restProps }) => (
  <VirtualTable.Container 
    style={{...style, msOverflowStyle: 'auto'}} 
    {...restProps}
  />
);

<Grid>
  ...
  <VirtualTable containerComponent={Container} />
  ...
</Grid>
```

**Closed** 2018-11-16 09:49 UTC
Labels: bug
