### ISSUE TITLE
Check the render method of `PluginHost$$1`.

### ISSUE THREAD

**Issue by cannibal** [DevExpress/devextreme-reactive#616] opened 2017-12-23 20:23 UTC
I am experiencing when trying the example on this page (https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/README.md):

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `PluginHost$$1`.

after installing as per the set up for material UI. I installed using yarn add as opposed to npm. I have added babel-polyfills to webpack as per the instructions.

Can any one advise what I might be doing wrong? I can see the demo works online.

Here are my deps:

  "dependencies": {
    "@devexpress/dx-react-core": "^1.0.0-beta.2",
    "@devexpress/dx-react-grid": "^1.0.0-beta.2",
    "@devexpress/dx-react-grid-material-ui": "^1.0.0-beta.2",
    "autoprefixer": "7.1.2",
    "babel-core": "6.25.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-react-app": "^3.0.2",
    "babel-runtime": "6.26.0",
    "bootlint": "^0.14.2",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "^2.3.0",
    "classnames": "^2.2.5",
    "create-react-class": "^15.6.2",
    "css-loader": "0.28.4",
    "dotenv": "4.0.0",
    "each-async": "^1.1.1",
    "electron": "v1.7.6",
    "eslint": "4.4.1",
    "eslint-config-react-app": "^2.0.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.35.0",
    "eslint-plugin-import": "2.7.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.1.0",
    "extract-text-webpack-plugin": "3.0.0",
    "file-loader": "0.11.2",
    "fs-extra": "3.0.1",
    "google-maps-react": "^1.1.2",
    "history": "^4.7.2",
    "html-webpack-plugin": "2.29.0",
    "indent-string": "^3.2.0",
    "jest": "^21.2.1",
    "jest-each": "^0.3.1",
    "jquery": "^3.2.1",
    "jscodeshift": "^0.3.32",
    "jump.js": "^1.0.2",
    "lodash": "^4.17.4",
    "material-ui": "^1.0.0-beta.25",
    "material-ui-codemod": "^1.0.0-beta.11",
    "material-ui-icons": "^1.0.0-beta.17",
    "node-sass-chokidar": "^0.0.3",
    "npm-run-all": "^4.1.1",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.6",
    "promise": "8.0.1",
    "prop-types": "^15.6.0",
    "react": "^15.6.1",
    "react-bootstrap": "^0.31.5",
    "react-bootstrap-carousel": "^1.2.0",
    "react-dev-utils": "^4.0.1",
    "react-dom": "^15.6.1",
    "react-flexbox-grid": "^2.0.0",
    "react-helmet": "^5.2.0",
    "react-redux": "^5.0.6",
    "react-redux-scroll": "^0.0.14",
    "react-responsive-carousel": "^3.1.26",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",
    "react-scroll": "^1.5.4",
    "react-scroll-to-component": "^1.0.1",
    "react-scrollbar-size": "^2.0.2",
    "react-slick": "^0.15.4",
    "react-tagsinput": "^3.19.0",
    "react-test-renderer": "^15.6.1",
    "react-transition-group": "^2.2.1",
    "react-waypoint": "^7.1.0",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-form": "^7.1.1",
    "redux-form-material-ui": "^5.0.0-beta.2",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.0",
    "reselect": "^3.0.1",
    "smoothscroll": "^0.4.0",
    "style-loader": "0.18.2",
    "styled-components": "^2.2.3",
    "svg-react-loader": "^0.4.5",
    "sw-precache-webpack-plugin": "0.11.4",
    "typeface-roboto": "^0.0.45",
    "url": "^0.11.0",
    "url-loader": "0.5.9",
    "webpack": "3.5.1",
    "webpack-dev-server": "2.7.1",
    "webpack-manifest-plugin": "1.2.1",
    "whatwg-fetch": "2.0.3",
    "wowjs": "^1.1.3"
  },

**Comment by mattaylor** [comment] 2017-12-23 20:28
ditto

**Comment by kvet** [comment] 2017-12-25 05:11
Hi,

We are closing this issue as a duplicate of #600.

**Closed by kvet** 2017-12-25 05:11 UTC
Labels: duplicate, question

**Comment by cannibal** [comment] 2017-12-28 18:29
Many thanks for getting back to me. Apologies for not spotting the original ticket.

Happy new year.
