### ISSUE TITLE
VirtualTableView fix left column

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#335] opened 2017-09-14 10:35 UTC
Hey guys,

somewhat related to #298 but with the VirtualTableView with a fixed height the fixed header bar is working great (though it would be nice to have the table fill the available space) but I think the option to fix the left most column is very important (for me at least).

Any thoughts on how one could implement this or do you guys have that functionality planned?

**Comment by kvet** [comment] 2017-09-15 07:31
Hi,
 
The virtual table is not an ordinary table in which such a task can be easily achieved with CSS. So, we have no workaround implementing fixed columns. We are considering implementing such functionality in the context of #293

**Comment by terndrup** [comment] 2017-09-15 12:37
Okay, I really need this functionality. Any ideas on how I could implement it myself?

**Comment by gsobolev** [comment] 2017-11-10 15:18
Hi,
 
We are closing this issue as a duplicate of #293.

**Closed by gsobolev** 2017-11-10 15:18 UTC
Labels: duplicate, question
