### ISSUE TITLE
A dependency not working 

### ISSUE THREAD

**Issue by dev-khalid** [DevExpress/devextreme-reactive#3651] opened 2023-05-31 05:55 UTC
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Grid

### Current Behaviour

In my next.js project Following error is occuring: 

> SyntaxError: Named export 'RRule' not found. The requested module 'rrule' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'rrule';
> const { RRuleSet, RRule } = pkg;
> 
> This error happened while generating the page. Any console logs will be displayed in the terminal window.

### Expected Behaviour

Please fix the issue so that i can run your package in my next.js application

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by omgaunicorn** [comment] 2023-06-05 05:48
This is a duplicate of #3644

**Comment by artem-kurchenko** [comment] 2023-06-09 16:40
Closing as duplicate

**Closed by artem-kurchenko** 2023-06-09 16:40 UTC
Labels: bug, STATE: Need response
