### ISSUE TITLE
How to remove Group

### ISSUE THREAD

**Issue by attiqeurrehman** [DevExpress/devextreme-reactive#1797] opened 2019-01-24 10:20 UTC
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I have few questions regarding Grouping, Fixed Column, and VirtualTable. 

1. **Grouping/GroupingState** adds an extra **th** with class **p-0**.
2. With **TableFixedColumns** group row text goes out of the view when you move the horizontal scroll. 
3. **VirtualTable** adds an empty row(s) sometimes one and sometimes two to offset the view, how can I add some class on it. 

### Expected Behaviour
1. I want to remove the extra **th** added.
2. I want the group heading to remain fixed with the column. 
3. I want to be able to add some class to these empty rows. 

### Steps to Reproduce
Please check out [this ](https://codesandbox.io/s/7wnkpm62w1)for more detail. 

### Environment

- dx-react-core: 1.10.0
- react: 16.7.0
- browser: Chrome
- bootstrap: 4.0
- reactstrap: 7.1.0

**Comment by ushkal** [comment] 2019-01-24 12:35
Hi,
1. These th and td elements are stub cells that are rendered to indent group data rows from its parent. Although you cannot prevent the Grid from rendering them, there is a workaround to hide them: set TableGroupRow.indentColumnWidth to 0.1. Would you please clarify why you need to hide these cells?
2. We have an [issue ](https://github.com/DevExpress/devextreme-reactive/issues/1798)with fixing a group row. It works incorrectly.
3. These rows are rendered using the VirtualTable.stubRowComponent property. You can add your class with the following code: 
```jsx
const StubRow = props => (
  <VirtualTable.StubRow {...props} className="custom-class" />
);
...
<VirtualTable stubRowComponent={StubRow} />
```

**Comment by attiqeurrehman** [comment] 2019-01-24 14:22
Hi,

>These th and td elements are stub cells that are rendered to indent group data rows from its parent. Although you cannot prevent the Grid from rendering them, there is a workaround to hide them: set TableGroupRow.indentColumnWidth to 0.1. Would you please clarify why you need to hide these cells?

Please take a look at [this](https://codesandbox.io/s/7wnkpm62w1), I don't want to show empty space it looks wierd. It looks like it's missing something.

**Comment by attiqeurrehman** [comment] 2019-01-24 14:34
Also, for question 3, the addition of empty rows with striped style messes up the styling and it looks like there is a slight flicker.

**Comment by attiqeurrehman** [comment] 2019-01-24 15:21
For question 2, provided reproduce code is a simple table. Are you going update it yourself?

**Comment by attiqeurrehman** [comment] 2019-01-25 08:11
For question 3, I was able to find the example from [here](https://github.com/DevExpress/devextreme-reactive/issues/1407).

**Comment by ushkal** [comment] 2019-01-25 09:39
@attiqeurrehman 
 
> For question 2, provided reproduce code is a simple table. Are you going update it yourself?
 

In this particular case it doesn't matter because the issue is reproduced with both VirtualTable and Table plugins.

**Comment by attiqeurrehman** [comment] 2019-01-29 14:14
@ushkal for question 3, even odd messes up because of the grouping. Any idea?

**Comment by ushkal** [comment] 2019-01-31 11:43
I've modified the example above. Please take a look: https://codesandbox.io/s/zxlpw09pnm.

**Comment by ushkal** [comment] 2019-02-01 12:45
@attiqeurrehman for Bootstrap 4, you can use 'style' and 'className' properties to stylize a component. [Here ](https://codesandbox.io/s/qvno96m489)is an updated sample.

**Comment by ushkal** [comment] 2019-02-06 14:41
@attiqeurrehman I'll close the issue. Feel free to reopen it or create another issue if you have further questions.

**Closed by ushkal** 2019-02-06 14:41 UTC
Labels: question
